In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Sara", "Ali", "Nina", "Reza", "Mina"],
    "Age": [25, 31, 22, 40, 29],
    "City": ["Oslo", "Trondheim", "Oslo", "Bergen", "Trondheim"],
    "Salary": [45000, 52000, 39000, 61000, 48000]
}

df = pd.DataFrame(data)

In [3]:
df

   Name  Age       City  Salary
0  Sara   25       Oslo   45000
1   Ali   31  Trondheim   52000
2  Nina   22       Oslo   39000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [4]:
df.head(5)

   Name  Age       City  Salary
0  Sara   25       Oslo   45000
1   Ali   31  Trondheim   52000
2  Nina   22       Oslo   39000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [5]:
df.head(5)  # 5 ردیف اول
df.tail(2)  # 2 ردیف آخر

   Name  Age       City  Salary
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [6]:
df.head(5)
df.tail(2)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [11]:
df.columns       # نام ستون‌ها

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [12]:
df.index         # index ردیف‌ها

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.shape

(5, 4)

In [15]:
df.Salary

0    45000
1    52000
2    39000
3    61000
4    48000
Name: Salary, dtype: int64

In [16]:
df[["City", "Name"]]

        City  Name
0       Oslo  Sara
1  Trondheim   Ali
2       Oslo  Nina
3     Bergen  Reza
4  Trondheim  Mina

In [17]:
df[["Age", "Name", "Salary"]]

   Age  Name  Salary
0   25  Sara   45000
1   31   Ali   52000
2   22  Nina   39000
3   40  Reza   61000
4   29  Mina   48000

In [18]:
result = df[df["Age"] > 28]
print(result)

   Name  Age       City  Salary
1   Ali   31  Trondheim   52000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000