In [1]:
import pandas as pd

In [2]:
data = {
    "Name": ["Sara", "Ali", "Nina", "Reza", "Mina"],
    "Age": [25, 31, 22, 40, 29],
    "City": ["Oslo", "Trondheim", "Oslo", "Bergen", "Trondheim"],
    "Salary": [45000, 52000, 39000, 61000, 48000]
}

df = pd.DataFrame(data)

In [3]:
df

   Name  Age       City  Salary
0  Sara   25       Oslo   45000
1   Ali   31  Trondheim   52000
2  Nina   22       Oslo   39000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [4]:
df.head(5)

   Name  Age       City  Salary
0  Sara   25       Oslo   45000
1   Ali   31  Trondheim   52000
2  Nina   22       Oslo   39000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [5]:
df.head(5)  # 5 ردیف اول
df.tail(2)  # 2 ردیف آخر

   Name  Age       City  Salary
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [6]:
df.head(5)
df.tail(2)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   City    5 non-null      str
 3   Salary  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [11]:
df.columns       # نام ستون‌ها

Index(['Name', 'Age', 'City', 'Salary'], dtype='str')

In [12]:
df.index         # index ردیف‌ها

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.shape

(5, 4)

In [15]:
df.Salary

0    45000
1    52000
2    39000
3    61000
4    48000
Name: Salary, dtype: int64

In [16]:
df[["City", "Name"]]

        City  Name
0       Oslo  Sara
1  Trondheim   Ali
2       Oslo  Nina
3     Bergen  Reza
4  Trondheim  Mina

In [17]:
df[["Age", "Name", "Salary"]]

   Age  Name  Salary
0   25  Sara   45000
1   31   Ali   52000
2   22  Nina   39000
3   40  Reza   61000
4   29  Mina   48000

In [18]:
result = df[df["Age"] > 28]
print(result)

   Name  Age       City  Salary
1   Ali   31  Trondheim   52000
3  Reza   40     Bergen   61000
4  Mina   29  Trondheim   48000

In [22]:
result = df[df["City"] == "Oslo"]
print(result)

   Name  Age  City  Salary
0  Sara   25  Oslo   45000
2  Nina   22  Oslo   39000

In [24]:
result = df[df["Salary"] >= 50000]
print(result)

   Name  Age       City  Salary
1   Ali   31  Trondheim   52000
3  Reza   40     Bergen   61000

In [33]:
result = df[(df["Age"] > 25) & (df["City"] == "Trondheim")]
print(result)

   Name  Age       City  Salary
1   Ali   31  Trondheim   52000
4  Mina   29  Trondheim   48000

In [34]:
df_sorted = df.sort_values(by='Age')

print(df_sorted)

   Name  Age       City  Salary
2  Nina   22       Oslo   39000
0  Sara   25       Oslo   45000
4  Mina   29  Trondheim   48000
1   Ali   31  Trondheim   52000
3  Reza   40     Bergen   61000

In [84]:
df_sorted = df.sort_values(by='Age', ascending=False)

print(df_sorted)

   Name  Age       City  Salary
3  Reza   40     Bergen   61000
1   Ali   31  Trondheim   52000
4  Mina   29  Trondheim   48000
0  Sara   25       Oslo   45000
2  Nina   22       Oslo   39000

In [85]:
df_sorted = df.sort_values(by="Salary", ascending=False)
print(df_sorted)

   Name  Age       City  Salary
3  Reza   40     Bergen   61000
1   Ali   31  Trondheim   52000
4  Mina   29  Trondheim   48000
0  Sara   25       Oslo   45000
2  Nina   22       Oslo   39000

In [86]:
df_sorted.set_index("Name", inplace=False)

      Age       City  Salary
Name
Reza   40     Bergen   61000
Ali    31  Trondheim   52000
Mina   29  Trondheim   48000
Sara   25       Oslo   45000
Nina   22       Oslo   39000

In [87]:
df_sorted.set_index("City", inplace=False)

           Name  Age  Salary
City
Bergen     Reza   40   61000
Trondheim   Ali   31   52000
Trondheim  Mina   29   48000
Oslo       Sara   25   45000
Oslo       Nina   22   39000

In [88]:
df_sorted.set_index("Name", inplace=False)

      Age       City  Salary
Name
Reza   40     Bergen   61000
Ali    31  Trondheim   52000
Mina   29  Trondheim   48000
Sara   25       Oslo   45000
Nina   22       Oslo   39000

In [89]:
df_indexed = df_sorted.set_index("Name", inplace=False)

In [113]:
df_indexed

      Age       City  Salary
Name
Reza   40     Bergen   61000
Ali    31  Trondheim   52000
Mina   29  Trondheim   48000
Sara   25       Oslo   45000
Nina   22       Oslo   39000

In [114]:
ali_info = df_indexed.loc["Ali"]

print(ali_info)

Age              31
City      Trondheim
Salary        52000
Name: Ali, dtype: object

In [94]:
df_indexed.loc["Ali", "Salary"]

np.int64(52000)

In [97]:
df_indexed.loc["Mina", ["Age","City"]]

Age            29
City    Trondheim
Name: Mina, dtype: object

In [98]:
df_indexed.iloc[0]

Age           40
City      Bergen
Salary     61000
Name: Reza, dtype: object

In [99]:
df_indexed.iloc[0, 1]

'Bergen'

In [103]:
Salary_in_the_third_arrow = df_indexed.iloc[2, 2]
print(Salary_in_the_third_arrow)

48000

In [112]:
df_indexed.iloc[1, [0, 2]]

Age          31
Salary    52000
Name: Ali, dtype: int64

In [110]:
df_indexed.iloc[1:4]

      Age       City  Salary
Name
Ali    31  Trondheim   52000
Mina   29  Trondheim   48000
Sara   25       Oslo   45000

In [120]:
df_indexed.iloc[1:4, 0:2]

      Age       City
Name
Ali    31  Trondheim
Mina   29  Trondheim
Sara   25       Oslo

In [122]:
numbers = list(range(1, 6))

In [124]:
years = list(range(1990, 2014))
print(years)

[1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]

In [126]:
years = list(map(str, range(1990, 2014)))
print(years)

['1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013']

In [3]:
import pandas as pd

data = {
    "Year": [2019, 2020, 2021, 2022, 2023, 2024],
    "Laptop": [120, 150, 180, 210, 260, 310],
    "Phone": [200, 230, 190, 270, 320, 370],
    "Tablet": [80, 95, 110, 105, 140, 160]
}

df = pd.DataFrame(data)

df

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105
4  2023     260    320     140
5  2024     310    370     160

In [3]:
df[df["Year"]==2020]

   Year  Laptop  Phone  Tablet
1  2020     150    230      95

In [4]:
sales_2024=df[df["Year"]==2024]

In [5]:
sales_2024[["Laptop","Phone","Tablet"]]

   Laptop  Phone  Tablet
5     310    370     160

In [10]:
sales_2024[["Laptop","Phone","Tablet"]].iloc[0]

Laptop    310
Phone     370
Tablet    160
Name: 5, dtype: int64

In [11]:
sales_2024[["Laptop", "Phone", "Tablet"]].iloc[0, 1]

np.int64(370)

In [12]:
sales_2024[["Laptop", "Phone", "Tablet"]].iloc[0, 2]

np.int64(160)

In [15]:
df[df["Year"]==2022][["Laptop","Phone","Tablet"]].iloc[0, 1]

np.int64(270)

In [16]:
df.iloc[3, 2]

np.int64(270)

In [21]:
df.iloc[2:4, 2:5]

   Phone  Tablet
2    190     110
3    270     105

In [22]:
df.iloc[1:4, 2:4]

   Phone  Tablet
1    230      95
2    190     110
3    270     105

In [25]:
df.iloc[2:5, 0:3]

   Year  Laptop  Phone
2  2021     180    190
3  2022     210    270
4  2023     260    320

In [26]:
df.loc[3, "Phone"]

np.int64(270)

In [28]:
df.loc[4, "Laptop"]

np.int64(260)

In [29]:
df.loc[2:4, ["Laptop", "Phone"]]

   Laptop  Phone
2     180    190
3     210    270
4     260    320

In [30]:
df.loc[1:3, ["Phone", "Tablet"]]

   Phone  Tablet
1    230      95
2    190     110
3    270     105

In [33]:
df.loc[df["Phone"]>250, ["Year","Phone"]]

   Year  Phone
3  2022    270
4  2023    320
5  2024    370

In [34]:
df.loc[df["Laptop"] > 200, ["Year", "Laptop"]]

   Year  Laptop
3  2022     210
4  2023     260
5  2024     310

In [35]:
df.loc[df["Tablet"] < 120, ["Year", "Tablet"]]

   Year  Tablet
0  2019      80
1  2020      95
2  2021     110
3  2022     105

In [36]:
df.loc[df["Phone"] >= 270, ["Year", "Phone", "Tablet"]]

   Year  Phone  Tablet
3  2022    270     105
4  2023    320     140
5  2024    370     160

In [4]:
df.sort_values("Laptop", ascending=True)

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105
4  2023     260    320     140
5  2024     310    370     160

In [5]:
df.sort_values("Laptop", ascending=False)

   Year  Laptop  Phone  Tablet
5  2024     310    370     160
4  2023     260    320     140
3  2022     210    270     105
2  2021     180    190     110
1  2020     150    230      95
0  2019     120    200      80

In [6]:
df.sort_values("Tablet", ascending=False)

   Year  Laptop  Phone  Tablet
5  2024     310    370     160
4  2023     260    320     140
2  2021     180    190     110
3  2022     210    270     105
1  2020     150    230      95
0  2019     120    200      80

In [9]:
filtered = df[df["Phone"] >= 230]

filtered.sort_values("Phone", ascending=False)

   Year  Laptop  Phone  Tablet
5  2024     310    370     160
4  2023     260    320     140
3  2022     210    270     105
1  2020     150    230      95

In [10]:
df[df["Phone"] >= 230].sort_values("Phone", ascending=False)

   Year  Laptop  Phone  Tablet
5  2024     310    370     160
4  2023     260    320     140
3  2022     210    270     105
1  2020     150    230      95

In [12]:
df[df["Laptop"] > 150].sort_values("Tablet", ascending=True)

   Year  Laptop  Phone  Tablet
3  2022     210    270     105
2  2021     180    190     110
4  2023     260    320     140
5  2024     310    370     160

In [13]:
df.head()

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105
4  2023     260    320     140

In [14]:
df.head(3)

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110

In [15]:
df.tail()

   Year  Laptop  Phone  Tablet
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105
4  2023     260    320     140
5  2024     310    370     160

In [16]:
df.tail(2)

   Year  Laptop  Phone  Tablet
4  2023     260    320     140
5  2024     310    370     160

In [17]:
df.head(4)

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105

In [18]:
df.tail(3)

   Year  Laptop  Phone  Tablet
3  2022     210    270     105
4  2023     260    320     140
5  2024     310    370     160

In [19]:
df.shape

(6, 4)

In [20]:
df.columns

Index(['Year', 'Laptop', 'Phone', 'Tablet'], dtype='str')

In [21]:
df.columns

Index(['Year', 'Laptop', 'Phone', 'Tablet'], dtype='str')

In [22]:
df.columns

Index(['Year', 'Laptop', 'Phone', 'Tablet'], dtype='str')

In [24]:
df.shape      # چند ردیف و ستون؟
df.columns    # اسم ستون‌ها چیه؟
df.dtypes     # نوع داده‌ها چیه؟

Year      int64
Laptop    int64
Phone     int64
Tablet    int64
dtype: object

In [3]:
import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Reza", "Mina"],
    "Age": [25, 30, None, 28],
    "Salary": [50000, None, 60000, 55000]
}

people = pd.DataFrame(data)

people

   Name   Age   Salary
0   Ali  25.0  50000.0
1  Sara  30.0      NaN
2  Reza   NaN  60000.0
3  Mina  28.0  55000.0

In [4]:
people["Age"].isnull().sum()

np.int64(1)

In [5]:
people.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [6]:
people.isnull().sum().sum()

np.int64(2)

In [7]:
people.isnull()

    Name    Age  Salary
0  False  False   False
1  False  False    True
2  False   True   False
3  False  False   False

In [8]:
people["Age"].mean()

np.float64(27.666666666666668)

In [9]:
people["Age"].fillna(people["Age"].mean())

0    25.000000
1    30.000000
2    27.666667
3    28.000000
Name: Age, dtype: float64

In [10]:
people

   Name   Age   Salary
0   Ali  25.0  50000.0
1  Sara  30.0      NaN
2  Reza   NaN  60000.0
3  Mina  28.0  55000.0

In [12]:
people["Age"] = people["Age"].fillna(people["Age"].mean())
people

   Name        Age   Salary
0   Ali  25.000000  50000.0
1  Sara  30.000000      NaN
2  Reza  27.666667  60000.0
3  Mina  28.000000  55000.0

In [16]:
people["Salary"] = people["Salary"].fillna(people["Salary"].mean())
people

   Name        Age   Salary
0   Ali  25.000000  50000.0
1  Sara  30.000000  55000.0
2  Reza  27.666667  60000.0
3  Mina  28.000000  55000.0

In [17]:
people.isnull().sum()

Name      0
Age       0
Salary    0
dtype: int64

In [31]:
data = {
    "Name": ["Ali", "Sara", "Reza", "Mina"],
    "Age": [25, 30, None, 28],
    "Salary": [50000, None, 60000, 55000]
}

people = pd.DataFrame(data)

In [29]:
people

   Name   Age   Salary
0   Ali  25.0  50000.0
1  Sara  30.0      NaN
2  Reza   NaN  60000.0
3  Mina  28.0  55000.0

In [20]:
people.dropna()

   Name   Age   Salary
0   Ali  25.0  50000.0
3  Mina  28.0  55000.0

In [27]:
people

   Name   Age   Salary
0   Ali  25.0  50000.0
3  Mina  28.0  55000.0

In [24]:
people=people.dropna()

In [30]:
people.dropna(subset=["Age"])

   Name   Age   Salary
0   Ali  25.0  50000.0
1  Sara  30.0      NaN
3  Mina  28.0  55000.0

In [32]:
people.dropna(subset=["Salary"])

   Name   Age   Salary
0   Ali  25.0  50000.0
2  Reza   NaN  60000.0
3  Mina  28.0  55000.0

In [3]:
import pandas as pd

data = {
    "Year": [2019, 2020, 2021, 2022, 2023, 2024],
    "Laptop": [120, 150, 180, 210, 260, 310],
    "Phone": [200, 230, 190, 270, 320, 370],
    "Tablet": [80, 95, 110, 105, 140, 160]
}

df = pd.DataFrame(data)

df

   Year  Laptop  Phone  Tablet
0  2019     120    200      80
1  2020     150    230      95
2  2021     180    190     110
3  2022     210    270     105
4  2023     260    320     140
5  2024     310    370     160

In [34]:
df["Laptop"].max()

np.int64(310)

In [35]:
df["Tablet"].min()

np.int64(80)

In [36]:
df["Phone"].mean()

np.float64(263.3333333333333)

In [37]:
df["Laptop"].sum()

np.int64(1230)

In [38]:
df[df["Phone"] == df["Phone"].max()]

   Year  Laptop  Phone  Tablet
5  2024     310    370     160

In [39]:
df["Phone"].max()

np.int64(370)

In [40]:
df[df["Phone"] == df["Phone"].max()]

   Year  Laptop  Phone  Tablet
5  2024     310    370     160

In [41]:
df[df["Laptop"] == df["Laptop"].min()]

   Year  Laptop  Phone  Tablet
0  2019     120    200      80

In [4]:
df["Category"] = ["Low", "Low", "Medium", "Medium", "High", "High"]

df

   Year  Laptop  Phone  Tablet Category
0  2019     120    200      80      Low
1  2020     150    230      95      Low
2  2021     180    190     110   Medium
3  2022     210    270     105   Medium
4  2023     260    320     140     High
5  2024     310    370     160     High

In [43]:
df["Category"].value_counts()

Category
Low       2
Medium    2
High      2
Name: count, dtype: int64

In [44]:
df["Laptop"].value_counts()

Laptop
120    1
150    1
180    1
210    1
260    1
310    1
Name: count, dtype: int64

In [5]:
df

   Year  Laptop  Phone  Tablet Category
0  2019     120    200      80      Low
1  2020     150    230      95      Low
2  2021     180    190     110   Medium
3  2022     210    270     105   Medium
4  2023     260    320     140     High
5  2024     310    370     160     High

In [ ]:
df.groupby("Category")["Laptop"].mean()

Category
High      285.0
Low       135.0
Medium    195.0
Name: Laptop, dtype: float64

In [47]:
df.groupby("Category")["Laptop"].mean()

Category
High      285.0
Low       135.0
Medium    195.0
Name: Laptop, dtype: float64

In [49]:
df.groupby("Category")["Phone"].mean()

Category
High      345.0
Low       215.0
Medium    230.0
Name: Phone, dtype: float64

In [50]:
df.groupby("Category")["Tablet"].max()

Category
High      160
Low        95
Medium    110
Name: Tablet, dtype: int64

In [6]:
df.groupby("Category")[["Laptop", "Phone"]].mean()

          Laptop  Phone
Category
High       285.0  345.0
Low        135.0  215.0
Medium     195.0  230.0

In [7]:
df.groupby("Category")[["Tablet","Laptop"]].sum()

          Tablet  Laptop
Category
High         300     570
Low          175     270
Medium       215     390